#!/usr/bin/env python3

import jinja2
import json
import os
import pick
import subprocess
import tempfile


ROOT_DIRECTORY = os.path.dirname(os.path.abspath(__file__))
CHROMIUM_PREFERENCES = "~/.config/chromium/Default/Preferences"

OPTIONS = {
    "Kabukicho": "GNyW9j9MsQI",
    "Brooks Falls": "2UIA8xOVcOs",
}

result = pick.pick(list(sorted(OPTIONS.keys())), "Select a stream:")
identifier = OPTIONS[result[0]]

environment = jinja2.Environment(loader=jinja2.FileSystemLoader(ROOT_DIRECTORY))
template = environment.get_template('template.html')


# Remove any indication that Chrome crashed to avoid a restore prompt.
preferences_path = os.path.expanduser(CHROMIUM_PREFERENCES)
preferences = None
with open(preferences_path, 'r') as fh:
    preferences = json.load(fh)
del preferences["profile"]["exit_type"]
with open(preferences_path, 'w') as fh:
    json.dump(preferences, fh)

with tempfile.NamedTemporaryFile(suffix=".html") as index:
    with open(index.name, 'w') as fh:
        fh.write(template.render(video=identifier))
    subprocess.check_call(["chromium-browser", "--kiosk", index.name])
