#!/usr/bin/env python3

import jinja2
import os
import pick
import subprocess


ROOT_DIRECTORY = os.path.dirname(os.path.abspath(__file__))

OPTIONS = {
    "Kabukicho": "GNyW9j9MsQI",
    "Brooks Falls": "2UIA8xOVcOs",
}

result = pick.pick(list(sorted(OPTIONS.keys())), "Select a stream:")
identifier = OPTIONS[result[0]]

environment = jinja2.Environment(loader=jinja2.FileSystemLoader(ROOT_DIRECTORY))
template = environment.get_template('template.html')

index = 'index.html'
with open(index, 'w') as fh:
    fh.write(template.render(video=identifier))

subprocess.check_call(["chromium-browser", "--kiosk", index])
