name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build:

    name: Build
    runs-on: raspbian-bullseye

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install dependencies
      run: scripts/install-dependencies.sh

    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE: ${{ github.ref == 'refs/heads/main' }}
        PRIVATE_KEY_FINGERPRINT: ${{ secrets.PRIVATE_KEY_FINGERPRINT }}
        PRIVATE_KEY_PASSPHRASE: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        ./scripts/build.sh

    - name: Archive the Debian package
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/*

    - name: Trigger repository update
      uses: peter-evans/repository-dispatch@v2
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        token: ${{ secrets.TOKEN }}
        repository: jbmorley/debian-repository
        event-type: build
