name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:

    name: Build
    runs-on: raspbian-bullseye

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install dependencies
      run: scripts/install-dependencies.sh

    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE: ${{ github.ref == 'refs/heads/main' }}
      run: |
        ./scripts/build.sh

    - name: Archive the Debian package
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/*
